networks:
  wordpress:
  proxy:
    external: true

services:
  db:
    image: docker.io/mariadb:12.3-noble
    container_name: wp-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - proxy
      - wordpress

  php:
    container_name: wp-php
    userns_mode: keep-id
    user: wp
    group_add:
      - wp
    build:
      context: .
      dockerfile: php.dockerfile
    volumes:
      - ./site:/srv/wp
      - ./php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - proxy
      - wordpress
