networks:
  wordpress:
  proxy:
    external: true

services:
  db:
    image: docker.io/mariadb:12.3-noble
    container_name: wp-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wp
      MYSQL_USER: wp
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
    volumes:
      - ./mariadb:/var/lib/mysql
    networks:
      - proxy
      - wordpress

  site:
    image: docker.io/wordpress:php8.4-fpm-alpine
    container_name: wp-site
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wp
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wp
    volumes:
      - ./site:/var/www/html
    networks:
      - proxy
      - wordpress
